name: Functional Tests
on: push

stages:
- stage: stage 1
  jobs: 
  - UI Tests:
      runs-on: ubuntu-22.04
      strategy:
        fail-fast: false
        matrix: 
          containers: [1]
      steps: 
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Cypress run
          uses: cypress-io/github-action@v5
  - API Tests: 
    dependsOn: UI Tests
    runs-on: ubuntu-22.04
      strategy:
        fail-fast: false
        matrix: 
          containers: [1]
      steps: 
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Cypress run
          uses: cypress-io/github-action@v5
